-- ============================================================
-- V8 - Seed additional tech skills, soft skills and languages
-- ============================================================

INSERT INTO skills (name) VALUES
    -- Programming languages
    ('Kotlin'),
    ('Scala'),
    ('PHP'),
    ('Ruby'),
    ('Swift'),
    ('Objective-C'),
    ('Dart'),
    ('R'),
    ('MATLAB'),
    ('Bash'),
    ('PowerShell'),

    -- Frontend
    ('Next.js'),
    ('Nuxt.js'),
    ('Svelte'),
    ('Tailwind CSS'),
    ('Redux'),
    ('React Query'),
    ('Webpack'),
    ('Vite'),
    ('Jest'),
    ('Vitest'),
    ('Playwright'),
    ('Cypress'),

    -- Backend
    ('Express.js'),
    ('NestJS'),
    ('Django'),
    ('Flask'),
    ('FastAPI'),
    ('Ruby on Rails'),
    ('Laravel'),
    ('ASP.NET Core'),
    ('Hibernate'),
    ('JPA'),
    ('Microservices'),
    ('Event-Driven Architecture'),
    ('WebSockets'),
    ('gRPC'),

    -- Databases and data
    ('MySQL'),
    ('MariaDB'),
    ('SQLite'),
    ('Redis'),
    ('Elasticsearch'),
    ('Kafka'),
    ('RabbitMQ'),
    ('Snowflake'),
    ('BigQuery'),
    ('ETL'),
    ('Data Warehousing'),
    ('Power BI'),
    ('Tableau'),

    -- Cloud, DevOps and infrastructure
    ('Azure'),
    ('Google Cloud'),
    ('Terraform'),
    ('Ansible'),
    ('Jenkins'),
    ('GitHub Actions'),
    ('GitLab CI'),
    ('Nginx'),
    ('Apache HTTP Server'),
    ('Prometheus'),
    ('Grafana'),
    ('Kibana'),
    ('Helm'),
    ('OpenShift'),

    -- Mobile and desktop
    ('React Native'),
    ('Flutter'),
    ('Android'),
    ('iOS'),
    ('Unity'),
    ('Electron'),

    -- Security and quality
    ('Cybersecurity'),
    ('OAuth2'),
    ('OpenID Connect'),
    ('Penetration Testing'),
    ('OWASP'),
    ('Unit Testing'),
    ('Integration Testing'),
    ('Test Automation'),
    ('QA'),
    ('Code Review'),

    -- AI and data science
    ('Deep Learning'),
    ('Natural Language Processing'),
    ('Computer Vision'),
    ('TensorFlow'),
    ('PyTorch'),
    ('Scikit-learn'),
    ('Pandas'),
    ('NumPy'),
    ('MLOps'),

    -- Product and design
    ('UI/UX Design'),
    ('Wireframing'),
    ('Prototyping'),
    ('Design Systems'),
    ('Product Management'),
    ('Business Analysis'),
    ('Technical Writing'),

    -- Soft skills
    ('Communication'),
    ('Teamwork'),
    ('Problem Solving'),
    ('Critical Thinking'),
    ('Adaptability'),
    ('Time Management'),
    ('Leadership'),
    ('Mentoring'),
    ('Attention to Detail'),
    ('Creativity'),
    ('Conflict Resolution'),
    ('Ownership'),
    ('Presentation Skills'),
    ('Stakeholder Management'),

    -- Languages
    ('English'),
    ('Romanian'),
    ('French'),
    ('German'),
    ('Spanish'),
    ('Italian'),
    ('Portuguese'),
    ('Dutch'),
    ('Polish'),
    ('Hungarian'),
    ('Russian'),
    ('Ukrainian'),
    ('Arabic'),
    ('Turkish'),
    ('Chinese'),
    ('Japanese'),
    ('Korean')
ON CONFLICT (name) DO NOTHING;
